categories: [Sequence Analysis]
description: Combines freebayes and mpileup files for use by vcf2pseudoalignment
name: consolidate_vcfs
owner: nml
remote_repository_url: https://irida.corefacility.ca/analysis-pipelines/snvphyl-galaxy
