#Galaxy - SNVPhyl
#
# VERSION       1.0

FROM phacnml/snvphyl-galaxy-1.0.1:1.0.1

MAINTAINER Aaron Petkau, aaron.petkau@gmail.com

# Set `allow_library_path_paste` to allow for linking to files within Docker Galaxy. Remove `--shared` so Docker does not oversubscribe jobs.
RUN sed -i -e 's/^#allow_library_path_paste.*/allow_library_path_paste = True/' /etc/galaxy/galaxy.ini && \
    sed -i -e 's/ --share//' /etc/galaxy/job_conf.xml
