#Galaxy - SNVPhyl
#
# VERSION       1.0

FROM phacnml/snvphyl-galaxy-0.2-beta-1:0.2-beta-1

MAINTAINER Aaron Petkau, aaron.petkau@gmail.com

# Set `allow_library_path_paste` to allow for linking to files within Docker Galaxy.
RUN sed -i -e 's/^#allow_library_path_paste.*/allow_library_path_paste = True/' /etc/galaxy/galaxy.ini
