# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "snvphyl-galaxy-1.0.1"

  config.vm.network :forwarded_port, guest: 8080, host: 48888
  config.vm.network :forwarded_port, guest: 22, host: 42222

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "https://irida.corefacility.ca/downloads/snvphyl-galaxy/vagrant/snvphyl-galaxy-1.0.1.box"
  config.vm.box_download_checksum = "7baa53c952cfa1138fae1042e6892f91dea0366605c2d89f8e0673da615bd10e"
  config.vm.box_download_checksum_type = "sha256"
end
