categories: [Sequence Analysis]
description: Generates multiple alignment of variant calls
name: vcf2snvalignment
owner: nml
remote_repository_url: https://github.com/phac-nml/snvphyl-galaxy
long_description: The SNVPhyl (Single Nucleotide Variant PHYLogenomics) pipeline is a pipeline for identifying Single Nucleotide Variants (SNV) within a collection of microbial genomes and constructing a phylogenetic tree. 
homepage_url: https://snvphyl.readthedocs.io/en/latest/
