categories: [Sequence Analysis]
description: SNVPhyl suite defining all dependencies for SNVPhyl
name: suite_snvphyl_0_5_0_dev
owner: nml
remote_repository_url: https://irida.corefacility.ca/analysis-pipelines/snvphyl-galaxy
