categories: [Sequence Analysis]
description: SNVPhyl suite defining all dependencies for SNVPhyl
name: suite_snvphyl_0_5_1_dev
owner: nml
remote_repository_url: https://github.com/phac-nml/snvphyl-galaxy
