categories: [Sequence Analysis]
description: SNVPhyl suite defining all dependencies for SNVPhyl
name: suite_snvphyl_1_2_1
owner: nml
remote_repository_url: https://github.com/phac-nml/snvphyl-galaxy
