categories: [Variant Analysis]
description: Generate alignment of SNVs from SNVPhyl variant table.
name: positions2snv_alignment
owner: nml
remote_repository_url: https://github.com/phac-nml/snvphyl-galaxy
long_description: The SNVPhyl (Single Nucleotide Variant PHYLogenomics) pipeline is a pipeline for identifying Single Nucleotide Variants (SNV) within a collection of microbial genomes and constructing a phylogenetic tree. 
homepage_url: https://snvphyl.readthedocs.io/en/latest/
